### ISSUE TITLE
[virtio-drivers] Windows SPICE agent

### ISSUE THREAD

**Issue by ghost** [DDoSolitary/chocolatey-packages#2]
Can you include inside package the [Windows SPICE agent](https://www.spice-space.org/download/windows/vdagent/vdagent-win-0.9.0/) of [spice-space](https://www.spice-space.org/download.html)?

I think it is the only not included in [virtio-win.iso](https://docs.fedoraproject.org/en-US/quick-docs/creating-windows-virtual-machines-using-virtio-drivers/) of Fedora.

PS: Or can be more easy use directly [spice-guest-tools](https://www.spice-space.org/download/windows/spice-guest-tools/), it include too the virtio-win drivers.

**Comment by DDoSolitary** [comment]
According to the official website spice-guest-tools only includes a subset of virtio drivers so it's not an ideal option.
> This installer contains some optional drivers and services that can be installed in Windows guest to improve SPICE performance and integration. This includes the qxl video driver and the SPICE guest agent (for copy and paste, automatic resolution switching, ...)
---
Since the SPICE agent isn't part of the libvirt project, I think maybe it's better to create a separate package for it.

**Comment by ghost** [comment]
> According to the official website spice-guest-tools only includes a subset of virtio drivers so it's not an ideal option.
> 
> > This installer contains some optional drivers and services that can be installed in Windows guest to improve SPICE performance and integration. This includes the qxl video driver and the SPICE guest agent (for copy and paste, automatic resolution switching, ...)

Yeah, I know about that description and I don't know about `.nsis` files. But if you see the source code of [win-guest-tools.nsis](https://gitlab.freedesktop.org/spice/win32/spice-nsis/blob/master/win-guest-tools.nsis), it seems use all the drivers included in virtio-win.iso (including a x86 and x64 version of vdagent and vdservice).

But you can are right and can be better a separate package for it. I don't know if would you be willing to create the [vdagent](https://www.spice-space.org/download/windows/vdagent/vdagent-win-0.9.0/) package.

In any case thank by the virtio-drivers package, and feel free of close this issue.

**Comment by DDoSolitary** [comment]
Package pushed: https://chocolatey.org/packages/spice-agent/
